# Generated by Django 4.0.6 on 2022-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_recebido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='data_entrada',
            field=models.DateTimeField(auto_now=True, unique_for_date=True),
        ),
    ]
