# Generated by Django 4.0.6 on 2022-08-07 16:01

import delivery.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_alter_delivery_recebido_por'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestador',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='casa',
        ),
        migrations.AddField(
            model_name='casa',
            name='moradores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.morador'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='modulo',
            field=models.ForeignKey(default=delivery.models.Box, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.box'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recebido_por',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
