# Generated by Django 4.0.6 on 2022-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_casa_moradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='nota_fiscal',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
