# Generated by Django 4.0.6 on 2022-09-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_delivery_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='nota_fiscal',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
