# Generated by Django 4.0.6 on 2022-09-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_delivery_nota_fiscal'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='local_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='aceite_condicoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='anfitriao_visita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.morador'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='convidado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='guests.convidado'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='evento',
            name='local_eventos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='guests.local_evento'),
        ),
    ]
