# Generated by Django 4.0.6 on 2022-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_local_evento_remove_evento_local_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='convidados_evento',
            field=models.ManyToManyField(to='guests.convidado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='qtd_convidados',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
